// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByv2gD7WIX_HuYNFOGZXLpqqXnhkIweBg',
    appId: '1:320318569495:web:d88c8b0ef61f0814aa7052',
    messagingSenderId: '320318569495',
    projectId: 'is381-2022-final-exam',
    authDomain: 'is381-2022-final-exam.firebaseapp.com',
    storageBucket: 'is381-2022-final-exam.appspot.com',
    measurementId: 'G-MX830SCJ3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4EX1p3nUS4Xx1krVZx6E21O_E_PIFSTQ',
    appId: '1:320318569495:android:3a9303d4541e52ceaa7052',
    messagingSenderId: '320318569495',
    projectId: 'is381-2022-final-exam',
    storageBucket: 'is381-2022-final-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdqvGwMZn5NSzEszJ_ACbeeFgBSYzclhU',
    appId: '1:320318569495:ios:54430966db3dae46aa7052',
    messagingSenderId: '320318569495',
    projectId: 'is381-2022-final-exam',
    storageBucket: 'is381-2022-final-exam.appspot.com',
    iosClientId: '320318569495-hi6idue6incp9gddb5k6qlkfn6t58v4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdqvGwMZn5NSzEszJ_ACbeeFgBSYzclhU',
    appId: '1:320318569495:ios:54430966db3dae46aa7052',
    messagingSenderId: '320318569495',
    projectId: 'is381-2022-final-exam',
    storageBucket: 'is381-2022-final-exam.appspot.com',
    iosClientId: '320318569495-hi6idue6incp9gddb5k6qlkfn6t58v4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );
}
