// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Owa4YFzGdYyjhrJB_0akdDbmHBsS7q0',
    appId: '1:604452351813:web:efe7315c83163e190c982c',
    messagingSenderId: '604452351813',
    projectId: 'is381-2022-montakarn',
    authDomain: 'is381-2022-montakarn.firebaseapp.com',
    storageBucket: 'is381-2022-montakarn.appspot.com',
    measurementId: 'G-7TW30YE2F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcBBgsjFx0iTtmc88KuO_x9-Wc7FkXDc',
    appId: '1:604452351813:android:f771b9596d2b0dab0c982c',
    messagingSenderId: '604452351813',
    projectId: 'is381-2022-montakarn',
    storageBucket: 'is381-2022-montakarn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDOIaJi3xNIAWQsamosvZvqlCerGIfi8',
    appId: '1:604452351813:ios:426f0abedd61cf7e0c982c',
    messagingSenderId: '604452351813',
    projectId: 'is381-2022-montakarn',
    storageBucket: 'is381-2022-montakarn.appspot.com',
    iosClientId: '604452351813-skg060rn0qodh85qtb802q4f4s9l4e4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDOIaJi3xNIAWQsamosvZvqlCerGIfi8',
    appId: '1:604452351813:ios:426f0abedd61cf7e0c982c',
    messagingSenderId: '604452351813',
    projectId: 'is381-2022-montakarn',
    storageBucket: 'is381-2022-montakarn.appspot.com',
    iosClientId: '604452351813-skg060rn0qodh85qtb802q4f4s9l4e4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
